### ISSUE TITLE
打包后无法创建文件

### ISSUE THREAD

**Issue by TinaHe** [jiayouzl/auto-py-to-app#1]
你好：
      我用这个程序打包成了可执行文件，程序可以正常运行，但是里面创建文件夹，创建文件的命令不能正常运行，我必须用sudo执行文件才可以。这块有没有什么解决方案啊？（第一次用mac系统，找了挺多教程没有解决掉）
谢谢！

**Comment by jiayouzl** [comment]
> 你好： 我用这个程序打包成了可执行文件，程序可以正常运行，但是里面创建文件夹，创建文件的命令不能正常运行，我必须用sudo执行文件才可以。这块有没有什么解决方案啊？（第一次用mac系统，找了挺多教程没有解决掉） 谢谢！

这个问题是你当前用户权限问题啊,跟程序本身没啥关系.

**Comment by TinaHe** [comment]
> > 你好： 我用这个程序打包成了可执行文件，程序可以正常运行，但是里面创建文件夹，创建文件的命令不能正常运行，我必须用sudo执行文件才可以。这块有没有什么解决方案啊？（第一次用mac系统，找了挺多教程没有解决掉） 谢谢！
> 
> 这个问题是你当前用户权限问题啊,跟程序本身没啥关系.

嗯嗯，是的，所以想咨询看看您这边有没有啥解决方案啊？

**Comment by jiayouzl** [comment]
> > > 你好： 我用这个程序打包成了可执行文件，程序可以正常运行，但是里面创建文件夹，创建文件的命令不能正常运行，我必须用sudo执行文件才可以。这块有没有什么解决方案啊？（第一次用mac系统，找了挺多教程没有解决掉） 谢谢！
> > 
> > 
> > 这个问题是你当前用户权限问题啊,跟程序本身没啥关系.
> 
> 嗯嗯，是的，所以想咨询看看您这边有没有啥解决方案啊？

直接创建一个管理员级别账号进行使用啊,macos跟linux类似,权限问题都比较烦的,macos一般都是自己用的系统非生产环境,就直接建管理员账号日常使用就行了.

还有个方法就是把需要权限的目录直接使用sudo chmod -R 777 文件名称直接一步到位.

**Comment by TinaHe** [comment]
好的，谢谢
